// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6Fp4CaiFmCQ8w2amKDxMK0DTmpHsScQ',
    appId: '1:1061709758038:web:0406b33cee84ec7a3305f7',
    messagingSenderId: '1061709758038',
    projectId: 'thuy-san-91d35',
    authDomain: 'thuy-san-91d35.firebaseapp.com',
    storageBucket: 'thuy-san-91d35.firebasestorage.app',
    measurementId: 'G-F1E29CVQDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzYh1XUEvOt_rpIyAVcMCb0SiL6pBgJY',
    appId: '1:1061709758038:android:d57ce1562b5c58583305f7',
    messagingSenderId: '1061709758038',
    projectId: 'thuy-san-91d35',
    storageBucket: 'thuy-san-91d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg0_1kxagGO3YmfBB0RdiacbbqH_oDS3s',
    appId: '1:1061709758038:ios:956b525946088d6d3305f7',
    messagingSenderId: '1061709758038',
    projectId: 'thuy-san-91d35',
    storageBucket: 'thuy-san-91d35.firebasestorage.app',
    iosBundleId: 'com.example.thuySan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg0_1kxagGO3YmfBB0RdiacbbqH_oDS3s',
    appId: '1:1061709758038:ios:956b525946088d6d3305f7',
    messagingSenderId: '1061709758038',
    projectId: 'thuy-san-91d35',
    storageBucket: 'thuy-san-91d35.firebasestorage.app',
    iosBundleId: 'com.example.thuySan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS6Fp4CaiFmCQ8w2amKDxMK0DTmpHsScQ',
    appId: '1:1061709758038:web:3c2e2bbb6ea0d21e3305f7',
    messagingSenderId: '1061709758038',
    projectId: 'thuy-san-91d35',
    authDomain: 'thuy-san-91d35.firebaseapp.com',
    storageBucket: 'thuy-san-91d35.firebasestorage.app',
    measurementId: 'G-P4ZZGJZSJ9',
  );
}
